steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'beta', 'run', 'jobs', 'update','${_IMAGE_NAME}', '--image', 'asia-south1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_COMMIT_SHA}', '--tasks', '${_NUM_TASKS}', '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID}', '--set-env-vars', 'SUBSCRIPTION_ID=${_SUBSCRIPTION_ID}', '--region','${_REGION}', '--service-account','${_SA}' ]
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'
    timeout: 180s
